### ISSUE TITLE
Crash on i button hover in Post Box [Fabric 1.20.1]

### ISSUE THREAD

**Issue by RhapsPerhaps** [MrCrayfish/MightyMail#1]
Hello! I didn't technically see this git linked for issues for this mod yet on Curseforge but I'm hoping it's still okay to post my crash here. 

This happened both in a heavy modded client, and when loading just this mod, framework, and fabric api. Whenever I hover over the little styled "i" button in the post box item the game crashes to desktop with the error below as the core of the crash report. 

I'm putting together a modpack for a small community and this mod would be perfect for us, but I can't chance them crashing the server constantly by just mousing over the wrong thing in the mail. (Even if I warned them. They'd do it anyway. I know they would.) 

Thank you! 

Framework Version: 0.6.16
Mighty Mail Version: 1.0.8
Fabric API Version: 0.87.0
Fabric Loader Version: 0.14.22
Minecraft Version: 1.20.1

```
[21:26:52] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:954) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1219) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
Caused by: java.lang.IllegalAccessError: class com.mrcrayfish.mightymail.platform.FabricClientHelper tried to access private field net.minecraft.class_7919.field_41103 (com.mrcrayfish.mightymail.platform.FabricClientHelper and net.minecraft.class_7919 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @66480dd7)
	at com.mrcrayfish.mightymail.platform.FabricClientHelper.setTooltipCache(FabricClientHelper.java:15) ~[mighty_mail-fabric-1.20.1-1.0.8.jar:?]
	at com.mrcrayfish.mightymail.client.util.ScreenHelper.createMultilineTooltip(ScreenHelper.java:41) ~[mighty_mail-fabric-1.20.1-1.0.8.jar:?]
	at com.mrcrayfish.mightymail.client.gui.screen.PostBoxScreen.method_2389(PostBoxScreen.java:208) ~[mighty_mail-fabric-1.20.1-1.0.8.jar:?]
	at net.minecraft.class_465.method_25394(class_465.java:100) ~[client-intermediary.jar:?]
	at com.mrcrayfish.mightymail.client.gui.screen.PostBoxScreen.method_25394(PostBoxScreen.java:138) ~[mighty_mail-fabric-1.20.1-1.0.8.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:945) ~[client-intermediary.jar:?]
	... 9 more
---- Minecraft Crash Report ----
// Who set us up the TNT?
Time: 2023-08-23 21:26:52
Description: Rendering screen
java.lang.IllegalAccessError: class com.mrcrayfish.mightymail.platform.FabricClientHelper tried to access private field net.minecraft.class_7919.field_41103 (com.mrcrayfish.mightymail.platform.FabricClientHelper and net.minecraft.class_7919 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @66480dd7)
	at com.mrcrayfish.mightymail.platform.FabricClientHelper.setTooltipCache(FabricClientHelper.java:15)
	at com.mrcrayfish.mightymail.client.util.ScreenHelper.createMultilineTooltip(ScreenHelper.java:41)
	at com.mrcrayfish.mightymail.client.gui.screen.PostBoxScreen.method_2389(PostBoxScreen.java:208)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at com.mrcrayfish.mightymail.client.gui.screen.PostBoxScreen.method_25394(PostBoxScreen.java:138)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at com.mrcrayfish.mightymail.platform.FabricClientHelper.setTooltipCache(FabricClientHelper.java:15)
	at com.mrcrayfish.mightymail.client.util.ScreenHelper.createMultilineTooltip(ScreenHelper.java:41)
	at com.mrcrayfish.mightymail.client.gui.screen.PostBoxScreen.method_2389(PostBoxScreen.java:208)
	at net.minecraft.class_465.method_25394(class_465.java:100)
	at com.mrcrayfish.mightymail.client.gui.screen.PostBoxScreen.method_25394(PostBoxScreen.java:138)
	at net.minecraft.class_437.method_47413(class_437.java:110)
-- Screen render details --
Details:
	Screen name: com.mrcrayfish.mightymail.client.gui.screen.PostBoxScreen
	Mouse location: Scaled: (226, 77). Absolute: (680.000000, 233.000000)
	Screen size: Scaled: (534, 300). Absolute: (1600, 900). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
-- Affected level --
Details:
	All players: 1 total; [class_746['RhapsPerhaps'/197, l='ClientLevel', x=-2.30, y=73.00, z=-3.31]]
	Chunk stats: 961, 609
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,79,0), Section: (at 0,15,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 527 game time, 527 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```

**Comment by MrCrayfish** [comment]
Fixed in 1.0.11
